name: heart_disease_mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas==2.2.3
      - numpy==1.26.4
      - scikit-learn==1.5.2
      - mlflow==2.19.0
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - imbalanced-learn==0.12.4